
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTERNODE_H
#define MASTERNODE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MasterNode_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MasterNode_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data MasterNode_Data;

#endif // MASTERNODE_H
